# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b45d192fa207c86b4fa7374e520dfc91e1469b4577e4931fad8257ade0d9d5f014761eee2c9e3c7774e6d7329181dd05757b3e7be4e1bd0b9d8d6366a32feb

test:
  secret_key_base: 5d7a36a7219abc3cd74f3bd226469a420a74e97cd15b7e93b26ec84eec9b77f87d64e60c0531adf41a4785b02c1da3cc03db63c1673526e5ef817bdd76115663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
